sanitize:
  tables:
    - name: users_field_data
      fields:
        - name: mail
          value: "SANITIZED_MAIL"
        - name: pass
          value: "SANITIZED_PASSWORD"

nodata:
  # Common cache tables.
  - cache_advagg_minify
  - cache_bootstrap
  - cache_config
  - cache_container
  - cache_data
  - cache_default
  - cache_discovery
  - cache_dynamic_page_cache
  - cache_entity
  - cache_geocoder
  - cache_library
  - cache_menu
  - cache_page
  - cache_postcode_lookup
  - cache_render
  - cache_rest
  - cache_toolbar
  # Webform user submissions.
  - webform_submission
  - webform_submission_data
  - webform_submission_log
  # Non-essential data.
  - captcha_sessions
  - history
  - flood
  - batch
  - queue
  - sessions
  - semaphore
  - search_api_item
  - search_api_task
  - search_dataset
  - search_index
  - search_total

ignore:
  - __ACQUIA_MONITORING__
